### ISSUE TITLE
Put all 3rd party libraries in one common folder.

### ISSUE THREAD

**Issue by adderly** [smellslikedonkey/DT3#12]

**Comment by smellslikedonkey** [comment]
The engine is split up into optional components. For example, DT3OpenAL has it's own 3rd Party dependencies that don't need to be in DT3Core if you aren't using OpenAL etc.

The only stuff in the DT3Core 3rdParty dir is the stuff needed to compile only the core. Make sense?

**Comment by adderly** [comment]
Yeap, i see now how you look at it. I really think that any piece of code needed by the engine on any os is part of a "Core". And you're right, it is not needed.
