### ISSUE TITLE
Move Platform dependencies out of the project file. (Where posible)

### ISSUE THREAD

**Issue by adderly** [smellslikedonkey/DT3#7]
@smellslikedonkey i think it is better to have specific platform implementation inside the engine. Even the creation of windows should be managed by the engine.
So when i start a project, i just see a custom start class, "AppDelegate" or something. 

As part of this, i could claim that any file from which the DT3Core depends on should be part of the "Core".

DT3Core/
--Platform/
-----Windows
-----Mac
-----Linux
-----Android
-----IOS

**Comment by adderly** [comment]
I´ve seen in many projects. only one header and multiple implementation:
Hal.hpp
Hal_unix.cpp
Hal_windows.cpp
Hal_mac.cpp

I think it can work better this way, for future multios implementations.

**Comment by smellslikedonkey** [comment]
I think I had it like this at one time but found a few reasons to give them each their own hpp. I don't really remember.

**Comment by adderly** [comment]
mmm... Maybe something about not complicating the cmake files?
